INSERT_EVENT_NAME = 'INSERT'
MODIFY_EVENT_NAME = 'MODIFY'
DELETE_EVENT_NAME = 'DELETE'

GOLF_CLUB = "GOLF_CLUB"
GOLF_COURSE = "GOLF_COURSE"
GOLF_ROUND = "GOLF_ROUND"
USER = "USER"

GOLF_CLUB_TAG = f"{GOLF_CLUB}{GOLF_CLUB}"
GOLF_COURSE_TAG = f"{GOLF_CLUB}{GOLF_COURSE}"
GOLF_ROUND_TAG = f"{USER}{GOLF_ROUND}"
USER_TAG = f"{USER}{USER}"
