version: '3.7'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: amazon/dynamodb-local:latest
    container_name: footwedge-dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
  elasticsearch:
    container_name: footwedge-search
    image: elasticsearch:7.5.2
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
  search-service-api:
    container_name: search-service-api
    image: tjburn70/search-service-api:latest
    build:
      context: ./search-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - SEARCH_ENGINE_URI=http://footwedge-search
      - PYTHONPATH=src
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - ./search-service/src:/src
    depends_on:
      - elasticsearch
  footwedge-api:
    container_name: footwedge-api
    image: tjburn70/footwedge-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - COGNITO_REGION=us-east-2
      - COGNITO_USER_POOL_ID=us-east-2_9tqIkGeQX
      - COGNITO_WEB_CLIENT_ID=24vuoscdcg85drk6c3bubtva2h
      - DYNAMO_DB_URL=http://footwedge-dynamodb-local:8000
      - FOOTWEDGE_DYNAMO_TABLE=FootwedgeTable
      - PYTHONPATH=src
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - ./api/src:/src
    depends_on:
      - dynamodb-local
